spring:
  application:
    name: spring-backend
  datasource:
    #url: jdbc:postgresql://${DATABASE_HOST}:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  test:
    database:
      replace: none
server:
  port: 8085