services:
#  nginx:
#    image: nginx:1-alpine
#    restart: always
#    ports:
#      - "8080:80"
#      - "8085:8085"
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#  api-server:
#    depends_on:
#      - db
#    image: forum:0.0.1-SNAPSHOT
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#    ports:
#      - '8085:8085'
#    networks:
#      - spring-network
#  redis:
#    image: redis:alpine
#    restart: always
#    ports:
#      - '6379:6379'
#    networks:
#      - spring-network
#    command: redis-server --save 30 1 --loglevel warning --requirepass redis
#    volumes:
#      - redis:/data
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - spring-network
    volumes:
      - db:/var/lib/postgresql/data
networks:
  spring-network:
    driver: bridge
volumes:
  redis:
    driver: local
  db:
    driver: local